"""empty message

Revision ID: 59c4cd2c59f5
Revises: 
Create Date: 2022-06-11 18:57:19.369665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c4cd2c59f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performers_address_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['performers_address_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_looking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weblinks_id', sa.Integer(), nullable=True),
    sa.Column('looking_venues', sa.Boolean(), nullable=False),
    sa.Column('seeking_description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['weblinks_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_sociallinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weblinks_id', sa.Integer(), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website_link', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['weblinks_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performers_genres_id', sa.Integer(), nullable=True),
    sa.Column('performers_genres', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['performers_genres_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show',
    sa.Column('show_venue_id', sa.Integer(), nullable=False),
    sa.Column('show_artist_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['show_artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['show_venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('show_venue_id', 'show_artist_id')
    )
    op.create_table('sociallinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sociallinks_id', sa.Integer(), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website_link', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['sociallinks_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_desc_seeking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeking_description_id', sa.Integer(), nullable=True),
    sa.Column('looking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['seeking_description_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_genres',
    sa.Column('genres_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('genres_venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genres_venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('genres_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genres')
    op.drop_table('venue_desc_seeking')
    op.drop_table('venue_address')
    op.drop_table('sociallinks')
    op.drop_table('show')
    op.drop_table('artists_genres')
    op.drop_table('artist_sociallinks')
    op.drop_table('artist_looking')
    op.drop_table('artist_address')
    op.drop_table('venue')
    op.drop_table('artist')
    # ### end Alembic commands ###
